### ISSUE TITLE
How does OnlyKey-gpg-agent SSH login?

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [svareille/OnlyKey-gpg-agent#4]
I found two issues blocking SSH logins,
1. The key created does not have the [A] Authentication attribute.
2. gpg-agent.exe Use "--server" instead of "--daemon" 。

    I tried manually modifying the key to add [A], using `command.arg("--daemon")` in the code, and found that it still can't interact with the OnlyKey hardware.

I don't know programming or English, and that's the limit of what I can do, and I hope the developers can help me.😫

**Comment by svareille** [comment]
Hi!

First of all, keep in mind that `ok-gpg-agent` is not currently designed to work with SSH. I could try to quick-fix some part of the code to make use of the built-in `gpg-agent`'s ssh capabilities, however I fear it would be harder than just a few rewrites.

Now for the issues you raised:
- For the first point, I will add a new parameter to select which flags to put on the generated key.
- For the second point, `gpg-agent` is started with `--server` because we need to interact with it using stdin/stdout. If we start it with `--daemon`, the main process of `gpg-agent` will exit and we won't be able to send commands to it. Worse, it will try to use the socket file we hijacked and either us or him won't be happy with it.
Why did you want to start `gpg-agent` with `--daemon`?

**Comment by wy16W2pIilK1xgqN** [comment]
谢谢你的解答。
期待能早日实现这个功能。
😁

**Comment by svareille** [comment]
The Authentication attribute can now be added with [v1.1.0](https://github.com/svareille/OnlyKey-gpg-agent/releases/tag/v1.1.0).

After looking into it, I conclude that making ok-gpg-agent compatible with SSH would require a massive addition to the code base. I am not willing to rewrite a complete gpg-agent. I think creating a driver to make the system believe that an OpenPGP Smartcard is attached would be more efficient. I will try that and maybe someday a new project will be published.
